### ISSUE TITLE
Add Markdown support in reviews

### ISSUE THREAD

**Issue by Varun-Kolanu** [Varun-Kolanu/gsoc-org-reviews-frontend#8]
Add github-flavored markdown support in writing (while posting) and wherever that review is rendered (review card and read more dialog). 

It needn't be too extensive, we should focus on baseline formatting features like lists, **bold**, *italic*, ~strikethrough~, headings etc.

## Must-haves
- We might in future add custom syntax (for mentioning users etc) if that aligns with the goals of this project. So to be prudent we should choose a markdown library that **supports extending custom syntax**.

- The implementation **must** support escaping characters.

- A `Preview` tab, just like here on github.

## Follow-ups
We can do many things to improve the UX:
- Add shortcut keys for inserting a markdown link syntax at current cursor.
- When typing a `*` or \`, the corresponding closing character can be automatically inserted rightwards to the cursor in the text area. 
- Pressing `enter` when writing a list should automatically insert `-` in the new line. (just like it happens here on github).
- Any other convenient behaviour.

We'd be fine if the implementation works mostly like github, since folks are used to writing here.

**Comment by criticic** [comment]
@issue-assigner claim
